### ISSUE TITLE
Infografia_Genaro Santiago Valentin

### ISSUE THREAD

**Issue by Valentiin01** [SistemasTecTlaxiaco/actividad-1-infografia-Valentiin01#2]
[Ciclo de vida del Software_ GENARO SANTIAGO VALENTÍN.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-infografia-Valentiin01/files/9465804/Ciclo.de.vida.del.Software_.GENARO.SANTIAGO.VALENTIN.pdf)

**Comment by mariagfh1228** [comment]
Calificación: 19.5

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
